eStyle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('',include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,

)

app_name='shop'

urlpatterns=[
    path('',HomeView.as_view(),name='home'),
    path('checkout/',CheckoutView.as_view(),name='checkout'),
    path('order-summary/',OrderSummaryView.as_view(),name='order-summary'),
    path('product/<slug>/',ItemDetailView.as_view(),name='product'),
    path('add-to-cart/<slug>',add_to_cart,name='add-to-cart'),
    path('remove-from-cart/<slug>',remove_from_cart,name='remove-from-cart'),
    path('remove-item-from-cart/<slug>',remove_single_item_from_cart,name='remove-single-item-from-cart'),
    ]

shop/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse


LABEL_CHOICES=(
 ('P','primary'),
 ('S','secondary'),
 ('D','danger')
)


#model to store the product info
class Item(models.Model):
    name=models.CharField(max_length=100)
    cost=models.FloatField()
    discount_cost=models.FloatField( blank=True ,null=True )     #not a required field
    colortag=models.CharField(choices=LABEL_CHOICES, max_length=1,blank=True ,null=True)
    tag=models.CharField(max_length=15,blank=True ,null=True)      #for giving different tags to products like bestseller, new etc.
    slug=models.SlugField()      #a unique identity for different products
    detail=models.TextField()
    photo=models.FileField(upload_to = 'images/', default = '')    #images are uploaded to media/images folder

    def __str__(self):
        return self.name    #when item is referenced its title is returned

    def get_absolute_url(self):
        return reverse("shop:product",kwargs={'slug':self.slug})     #unique url for every product due to its slug

    def get_add_item_to_cart_url(self):
        return reverse("shop:add-to-cart",kwargs={'slug':self.slug})    #url for adding an item to cart

    def get_remove_item_from_cart_url(self):
        return reverse("shop:remove-from-cart",kwargs={'slug':self.slug})    #url for adding an item to cart



#model to obtain the info of products which are ordered by a particular user
class OrderItem(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,
                           on_delete=models.CASCADE)    #obtaining user info from allauth
    item=models.ForeignKey(Item, on_delete=models.CASCADE)     #for obtaining product info from Item model
    number=models.IntegerField(default=1)
    ordered=models.BooleanField(default=False)   #whather the product has been added to cart or not


    def __str__(self):
        return f"{self.number} of {self.item.name}"      #when ordered item is referenced its title and quantity is returned

    def get_total_product_cost(self):
        return self.number * self.item.cost   #returns an item price according to its quantity

    def get_total_discount_product_cost(self):
        return self.number * self.item.discount_cost   #for calculating price in case of a discount

    def get_saved_cost(self):
        return self.get_total_product_cost()-self.get_total_discount_product_cost()

    def get_final_cost(self):
        if self.item.discount_cost:
            return self.get_total_discount_product_cost()
        else:
            return self.get_total_product_cost()

#model to obtain info about orders placed by particular user
class Order(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,
                           on_delete=models.CASCADE)    #obtaining user info from allauth
    items=models.ManyToManyField(OrderItem)      #a product can be present in more than one orders(of different users)
    order_begin_date=models.DateTimeField(auto_now_add=True)
    order_placed_date=models.DateTimeField()
    ordered=models.BooleanField(default=False)      #whather the order has been placed or not
    address=models.ForeignKey(
            'Address',on_delete=models.SET_NULL,blank=True,null=True)   #for obtaining user address and other info to deliver the product

    def __str__(self):
        return self.user.username           #returns the username who placed the order

    def get_order_cost(self):
        order_cost=0
        for order_item in self.items.all():
            order_cost+=order_item.get_final_cost()
        return order_cost                        #returns the order total for a particular order


#model for storing data entered by user through checkout form
class Address(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,
                           on_delete=models.CASCADE)     #obtaining user info from allauth for storing address info
    first_name=models.CharField(max_length=50)
    last_name=models.CharField(max_length=50)
    street_address=models.CharField(max_length=100)
    apartment_address=models.CharField(max_length=100)
    country=models.CharField(max_length=15)
    city=models.CharField(max_length=15)    #constraits are applied in form fields beacuse data is entered by user through forms
    postal_code=models.CharField(max_length=5)
    phone=models.CharField(max_length=13)

    def __str__(self):
        return '%s %s %s' %(self.street_address,self.apartment_address,self.city)
          #when user address is referenced the street and apartment address, city and country is returned

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/icons.ico' %}" />
  <title>
  {% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

{% include "navbar.html" %}

<body>

  <div class="mt-5 pt-4">
    {% if messages %}
    <br>
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-3 mb-2" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %}
  {% endif %}
  </div>

      {% block content %}
      {% endblock content %}

      {% block extra_body %}
      {% endblock %}

      {% include "footer.html" %}
      {% include "scripts.html" %}

  </body>
  </html>

templates/checkout.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}Checkout - eStyle{% endblock %}

{% block content %}

  <!--Main layout-->
  <main>
    <div class="container wow fadeIn ">

      <!-- Heading -->
      <br><h2 class="my-5 text-center">Checkout Form</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-12 mb-4">

          <!--Card-->
          <div class="card">
            
            <!-- <form>
              {% csrf_token %}
              {{form| crispy}}
              <button class='btn btn-primary 'type="submit">Checkout</button>
            </form> -->

            <!--Card content-->
            <form method="POST" class="card-body">
              {% csrf_token %}
              <!--Grid row-->
              <div class="row">

            <!--Grid column-->
             <div class="col-md-6 mb-2">
             <!--firstName-->
             <div class="md-form ">
                {{ form.first_name }}
                <label for="firstName" class="">First name</label>
             </div>

             </div>
             <!--Grid column-->

             <!--Grid column-->
             <div class="col-md-6 mb-2">

             <!--lastName-->
             <div class="md-form">
                {{ form.last_name }}
                <label for="lastName" class="">Last name</label>
              </div>

              </div>
              <!--Grid column-->

              </div>
              <!--Grid row-->

              <!--address-->
              <div class="md-form mb-5">
                {{form.street_address}}
                <label for="address" class="">Address</label>

              </div>

              <!--address-2-->
              <div class="md-form mb-5">
                {{form.apartment_address}}
                <label for="address-2" class="">Address 2 (optional)</label>
              </div>

              <!--Grid row-->
              <div class="row">

                <!--Grid column-->
                <div class="col-lg-4 col-md-12 mb-4">

                  <label for="country">Country</label>
                  {{form.country}}
                  <div class="invalid-feedback">
                    Please select a valid country.
                  </div>
                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-4 col-md-12 mb-4">

                  <label for="country">City</label>
                  {{form.city}}
                  <div class="invalid-feedback">
                    Please select a valid city.
                  </div>

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">

                  <label for="zip">Postal Code</label>
                  {{form.postal_code}}
                  <div class="invalid-feedback">
                  Postal code required.
                  </div>

                </div>
                <!--Grid column-->



              </div>
              <!--Grid row-->



              <!--phone-->
              <div class="md-form mb-3">
                {{form.phone}}
                <label for="phone" class="">Phone</label><br>
              </div>

              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

            </form>

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->


      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

{% endblock content %}

templates/footer.html
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <p><strong>Contact Us:</strong><i class="fas fa-phone mr-2 ml-5"></i>+92 309 9876456<i class="fas fa-envelope ml-4 mr-2"></i>estyle@gmail.com</p>

    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright: eStyle
    </div>
    <!--/.Copyright-->

  </footer>

templates/home.html
{% extends "base.html" %}

{% block head_title %}eStyle{% endblock %}
{% block content %}
{% load static %}


<!--Carousel Wrapper-->
<div id="carousel-example-1z" class="carousel slide carousel-fade" data-ride="carousel">

  <!--Indicators-->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-1z" data-slide-to="1"></li>
    <li data-target="#carousel-example-1z" data-slide-to="2"></li>
  </ol>
  <!--/.Indicators-->

  <!--Slides-->
  <div class="carousel-inner" role="listbox">

    <!--First slide-->
    <div class="carousel-item active">
      <div class="view" style="background-image: url('{% static 'img/c1.jpg' %}'); background-repeat: no-repeat; background-size: cover;">

        <!-- Mask & flexbox options-->
        <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

          <!-- Content -->
          <div class="text-center white-text mx-5 wow fadeIn">
            <img src="{% static 'img/Caro.png' %}" alt="">
            <!-- <h1 class="mb-4" style="font-family: cursive, serif; font-style:italic;">
              <strong><b>eStyle</b></strong>
            </h1> -->

            <p>
              <strong><font size="+3">DO IT YOUR WAY</font></strong>
            </p>

            <p class="mb-4 d-none d-md-block" style="font-family: garamond;">
              <br><strong><font size="+2">eStyle provides you with the latest collections of comfortable and elegant ladies clothing.</font></strong>
            </p>

          </div>
          <!-- Content -->

        </div>
        <!-- Mask & flexbox options-->


      </div>
    </div>
    <!--/First slide-->

    <!--Second slide-->
    <div class="carousel-item">
      <div class="view" style="background-image: url('{% static 'img/c2.jpg' %}'); background-repeat: no-repeat; background-size: cover;">

        <!-- Mask & flexbox options-->
        <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

          <!-- Content -->
          <div class="text-center white-text mx-5 wow fadeIn">
            <img src="{% static 'img/Caro.png' %}" alt="">
            <!-- <h1 class="mb-4" style="font-family: cursive, serif; font-style:italic">
              <strong><b>eStyle</b></strong>
            </h1> -->

            <p>
              <strong><font size="+3">DO IT YOUR WAY</font></strong>
            </p>

            <p class="mb-4 d-none d-md-block" style="font-family: garamond;">
              <br><strong><font size="+2">eStyle provides you with the latest collections of comfortable and elegant ladies clothing.</font></strong>
            </p>
          </div>
          <!-- Content -->

        </div>
        <!-- Mask & flexbox options-->


      </div>
    </div>
    <!--/Second slide-->

    <!--Third slide-->
    <div class="carousel-item">
      <div class="view" style="background-image: url('{% static 'img/c3.jpg' %}'); background-repeat: no-repeat; background-size: cover;">

        <!-- Mask & flexbox options-->
        <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

          <!-- Content -->

          <div class="text-center white-text mx-5 wow fadeIn">
            <img src="{% static 'img/Caro.png' %}" alt="">
            <!-- <h1 class="mb-4" style="font-family: cursive, serif; font-style:italic">
              <strong><b>eStyle</b></strong>
            </h1> -->

            <p>
              <strong><font size="+3">DO IT YOUR WAY</font></strong>
            </p>

            <p class="mb-4 d-none d-md-block" style="font-family: garamond;">
              <br><strong><font size="+2">eStyle provides you with the latest collections of comfortable and elegant ladies clothing.</font></strong>
            </p>
          </div>
          <!-- Content -->

        </div>
        <!-- Mask & flexbox options-->

      </div>
    </div>
    <!--/Third slide-->

  </div>
  <!--/.Slides-->

  <!--Controls-->
  <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  <!--/.Controls-->

</div>
<!--/.Carousel Wrapper-->

  <!--Main layout-->
  <main>
    <div class="container">
      <br>

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Our Products</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">
          {% for item in object_list %}

          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                <img src="{{ item.photo.url }}" class="card-img-top" alt="{{item.name}}">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h8>Clothing</h8>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.name }}
                      <span class="badge badge-pill {{item.get_colortag_display}}-color">{{item.tag}}</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>Rs.
                  {% if item.discount_cost %}
                  {{ item.discount_cost }}
                  {% else %}
                  {{ item.cost }}
                  {% endif %}
                  </strong>
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          <!--Grid column-->
          {% endfor %}
        </div>
        <!--Grid row-->

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          <!--Arrow left-->
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}
      <!--Pagination-->

    </div>
  </main>
  <!--Main layout-->


{% endblock content %}

templates/item_list.html
{% extends "base.html" %}


{% block content %}
<h2>Here is the list of items</h2>

{% for item in items %}
    {{item}}
{% endfor %}



{% endblock content %}

templates/navbar.html
{% load static %}

<!-- Navbar -->
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar" >
  <div class="container">

    <!-- Brand -->
    <a class="navbar-brand waves-effect" href="/">
      <img src="{% static 'img/Logos.png' %}" alt="Logo" style="width:65px;height:70px;">
    </a>

    <!-- Collapse -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <!-- Left -->
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link waves-effect" href="/"><font size="+2">Home</font>
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="/checkout">
          <font size="+2">Checkout</font></a>
      </ul>

      <!-- Right -->
      <ul class="navbar-nav nav-flex-icons">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a style='color:black;' href="{% url 'shop:order-summary' %}"class="nav-link waves-effect">
            <i class="fas fa-shopping-cart" style="color:#808080"></i>
            <span style='color:black;' class="clearfix d-none d-sm-inline-block"><font size="+2">Cart</font></span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
            <span class="clearfix d-none d-sm-inline-block"><font size="+2">Log Out</font></span>
          </a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_login' %}">
            <span class="clearfix d-none d-sm-inline-block"><font size="+2">Log In</font></span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
            <span class="clearfix d-none d-sm-inline-block"><font size="+2">Sign Up</font></span>
          </a>
        </li>
        {% endif %}
      </ul>

    </div>

  </div>
</nav>
<!-- Navbar -->

templates/order_summary.html
{% extends "base.html" %}
{% block head_title %}Order Summary - eStyle{% endblock %}

{% block content %}

{% load static %}

  <!--Main layout-->
  <main>
    <div class="container">
      <div class="table-responsive text-nowrap">
        <br><br><br><h2>Order Summary</h2>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Item Title</th>
              <th scope="col">Price</th>
              <th scope="col">Quantity</th>
              <th scope="col">Total Item Price</th>

            </tr>
          </thead>
          <tbody>
            {% for order_item in object.items.all %}
            <tr>
              <th scope="row">{{ forloop.counter }}</th>
              <td>{{ order_item.item.name }}</td>
              <td>{{ order_item.item.cost }}</td>
              <td>
                <a href="{% url 'shop:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                {{ order_item.number }}
                <a href="{% url 'shop:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
              </td>
              <td>
              {% if order_item.item.discount_cost %}
                  Rs.{{ order_item.get_total_discount_product_cost }}
                  <span class="badge badge-primary">Saving Rs.{{ order_item.get_saved_cost }}</span>
              {% else %}
                  Rs.{{ order_item.get_total_product_cost }}
              {% endif %}
              <a style='color:red;' href="{% url 'shop:remove-from-cart' order_item.item.slug %}">
                <i class="fas fa-trash float-right"></i>
              </a>
              </td>
            </tr>
            {% empty %}
            <tr>
              <td colspan="5">Your cart is empty.</td>
            </tr>
            <tr>
              <td colspan="5"><br>
              <a class='btn btn-primary float-right' href="/">Continue Shopping</a>
              </td>
            </tr>
            {% endfor %}
            {% if object.get_order_cost %}
            <tr>
              <td colspan="4"><b>Order Total</b></td>
              <td><b>Rs.{{ object.get_order_cost }}</b></td>
            </tr>
            <tr>
              <td colspan="5"><br>
              <a class='btn btn-default float-right ml-3' href="/checkout/">Proceed to Checkout</a>
              <a class='btn btn-primary float-right' href="/">Continue Shopping</a>
              </td>
            </tr>
            {% endif %}
          </tbody>
        </table>

      </div>

    </div>
    <br><br><br><br><br><br><br><br><br><br>
  </main>
  <!--Main layout-->


{% endblock content %}

templates/product.html
{% extends "base.html" %}
{% block content %}

{% block head_title %}{{ item.name }} - eStyle{% endblock %}

{% load static %}

  <!--Main layout-->
  <main class="mt-2 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="{{object.photo.url}}" class="img-fluid" height="600" width="450" alt="{{object.name}}">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">Clothing</span>
              </a>

            </div>

            <p class="lead">
              {% if object.discount_cost %}
              <span class="mr-1">
                <del>Rs.{{object.cost}}</del>
              </span>
              <span>Rs.{{object.discount_cost}}</span>
              {% else %}
              <span>Rs.{{ object.cost }}</span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>3 Piece<br>{{ object.detail }}<br><br></p>

           {% comment %}
           <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> {% endcomment %}
            <a href="{{ object.get_add_item_to_cart_url }}" class="btn btn-primary my-0 p">
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
              </a>
              <a href="{{ object.get_remove_item_from_cart_url }}" class="btn btn-danger my-0 p">
                Remove from cart
                </a>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->


    </div>
  </main>
  <!--Main layout-->

{% endblock content %}

templates/scripts.html
{% load static %}

<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();

</script>